# Generated by Django 4.2.5 on 2023-09-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destinationimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detailed_destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. Max length: 100 characters', max_length=100, unique=True, verbose_name='Destination Name')),
                ('place', models.CharField(help_text='Required. Max length: 100 characters', max_length=100, verbose_name='Place')),
                ('days', models.IntegerField(default=5, verbose_name='Days')),
                ('price', models.DecimalField(decimal_places=2, default=20000, max_digits=9, verbose_name='Price')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Rating')),
                ('description', models.TextField(help_text='Required', verbose_name='Description')),
                ('reviews', models.TextField(blank=True, null=True, verbose_name='Reviews')),
                ('package_instructions', models.TextField(blank=True, null=True, verbose_name='Package Instructions')),
            ],
        ),
    ]
